from __future__ import annotations

ITEM_ZH = {
    "Doran's Ring": "多兰之戒",
    "Doran's Blade": "多兰之刃",
    "Doran's Bow": "多兰之弓",
    "Doran's Helm": "多兰头盔",
    "Doran's Shield": "多兰之盾",
    "Health Potion": "生命药水",
    "Refillable Potion": "复用型药水",
    "Tear of the Goddess": "女神之泪",
    "Dark Seal": "黑暗封印",
    "Scorchclaw Pup": "焰爪猫幼崽",
    "Gustwalker Hatchling": "踏苔蜥幼苗",
    "Mosstomper Seedling": "踏苔蜥幼苗",
    "Plated Steelcaps": "铁板靴",
    "Mercury's Treads": "水银之靴",
    "Ionian Boots of Lucidity": "明朗之靴",
    "Berserker's Greaves": "狂战士胫甲",
    "Sorcerer's Shoes": "法师之靴",
    "Boots of Swiftness": "轻灵之靴",
    "Sunfire Aegis": "日炎圣盾",
    "Hollow Radiance": "败魔之光",
    "Frozen Heart": "冰霜之心",
    "Thornmail": "荆棘之甲",
    "Randuin's Omen": "兰顿之兆",
    "Dead Man's Plate": "亡者的板甲",
    "Kaenic Rookern": "败魔",
    "Force of Nature": "自然之力",
    "Spirit Visage": "振奋盔甲",
    "Jak'Sho, The Protean": "千变者贾修",
    "Unending Despair": "无终恨意",
    "Endless Hunger": "无尽饥渴",
    "Iceborn Gauntlet": "冰脉护手",
    "Eclipse": "星蚀",
    "Sundered Sky": "焚天",
    "Death's Dance": "死亡之舞",
    "Sterak's Gage": "斯特拉克的挑战护手",
    "Guardian Angel": "守护天使",
    "Bloodthirster": "饮血剑",
    "Black Cleaver": "黑色切割者",
    "Maw of Malmortius": "玛莫提乌斯之噬",
    "Wit's End": "智慧末刃",
    "Trinity Force": "三相之力",
    "Stridebreaker": "挺进破坏者",
    "Titanic Hydra": "巨型九头蛇",
    "Ravenous Hydra": "贪欲九头蛇",
    "Blade of The Ruined King": "破败王者之刃",
    "Youmuu's Ghostblade": "幽梦之灵",
    "Hubris": "狂妄",
    "Opportunity": "机遇",
    "Voltaic Cyclosword": "感电三轮刃",
    "Edge of Night": "夜之锋刃",
    "The Collector": "收集者",
    "Serylda's Grudge": "赛瑞尔达的怨恨",
    "Infinity Edge": "无尽之刃",
    "Rapid Firecannon": "疾射火炮",
    "Lord Dominik's Regards": "多米尼克领主的致意",
    "Kraken Slayer": "海妖杀手",
    "Statikk Shiv": "斯塔缇克电刃",
    "Navori Flickerblade": "纳沃利烁刃",
    "Phantom Dancer": "幻影之舞",
    "Runaan's Hurricane": "卢安娜的飓风",
    "Mortal Reminder": "凡性的提醒",
    "Terminus": "界弓",
    "Stormrazor": "岚切",
    "Hexoptics C44": "海克斯光学C44",
    "Mercurial Scimitar": "水银弯刀",
    "Blackfire Torch": "黑火炬",
    "Malignance": "残疫",
    "Lich Bane": "巫妖之祸",
    "Nashor's Tooth": "纳什之牙",
    "Guinsoo's Rageblade": "鬼索的狂暴之刃",
    "Mejai's Soulstealer": "梅贾的窃魂卷",
    "Stormsurge": "风暴狂涌",
    "Liandry's Torment": "兰德里的折磨",
    "Hextech Rocketbelt": "海克斯科技火箭腰带",
    "Rylai's Crystal Scepter": "瑞莱的冰晶节杖",
    "Horizon Focus": "视界专注",
    "Cosmic Drive": "星界驱驰",
    "Luden's Companion": "卢登的伙伴",
    "Shadowflame": "影焰",
    "Rabadon's Deathcap": "灭世者的死亡之帽",
    "Zhonya's Hourglass": "中娅沙漏",
    "Seeker's Armguard": "探索者的护臂",
    "Void Staff": "虚空之杖",
    "Banshee's Veil": "女妖面纱",
    "Moonstone Renewer": "月石再生器",
    "Ardent Censer": "炽热香炉",
    "Redemption": "救赎",
    "Mikael's Blessing": "米凯尔的祝福",
    "Locket of the Iron Solari": "钢铁烈阳之匣",
    "World Atlas": "世界地图",
    "Celestial Opposition": "星界据守",
    "Dream Maker": "圆梦使者",
    "Solstice Sleigh": "冬至雪橇",
    "Zaz'Zak's Realmspike": "扎兹沙克的溃口",
    "Bloodsong": "血鸣",
    "Knight's Vow": "骑士之誓",
    "Bandlepipes": "班德尔号角",
    "Protoplasm Harness": "原生质束带",
    "Shurelya's Battlesong": "舒瑞娅的战歌",
    "Imperial Mandate": "帝国指令",
    "Staff of Flowing Water": "流水法杖",
    "Echoes of Helia": "海利亚的回响",
    "Dawncore": "黎明核心",
    "Zeke's Convergence": "基克的聚合",
    "Warmog's Armor": "狂徒铠甲",
    "Heartsteel": "心之钢",
    "Hullbreaker": "破舰者",
    "Spear of Shojin": "朔极之矛",
    "Experimental Hexplate": "海克斯注力刚壁",
    "Overlord's Bloodmail": "霸王血铠",
    "Rod of Ages": "时光之杖",
    "Archangel's Staff": "大天使之杖",
    "Manamune": "魔宗",
    "Luden's Echo": "卢登的回声",
    "Cryptbloom": "隐秘之花",
    "Morellonomicon": "莫雷洛秘典",
    "Riftmaker": "峡谷制造者",
    "Bloodletter's Curse": "血色诅咒",
    "Axiom Arc": "公理圆弧",
    "Serpent's Fang": "巨蛇之牙",
    "Essence Reaver": "夺萃之镰",
    "Immortal Shieldbow": "不朽盾弓",
    "Gluttonous Greaves": "贪婪胫甲",
    "Actualizer": "现实校准器",
    "Bastionbreaker": "壁垒破坏者",
    "Dusk and Dawn": "暮与晨",
    "Fiendhunter Bolts": "恶魔猎手弩矢",
    "Whispering Circlet": "低语环冠",
}

RUNE_ZH = {
    "Resolve": "坚决",
    "Precision": "精密",
    "Domination": "主宰",
    "Sorcery": "巫术",
    "Inspiration": "启迪",
    "Grasp of the Undying": "不灭之握",
    "Aftershock": "余震",
    "Guardian": "守护者",
    "Demolish": "爆破",
    "Font of Life": "生命源泉",
    "Shield Bash": "护盾猛击",
    "Conditioning": "调节",
    "Second Wind": "复苏之风",
    "Bone Plating": "骸骨镀层",
    "Overgrowth": "过度生长",
    "Revitalize": "复苏",
    "Unflinching": "坚定",
    "Press the Attack": "强攻",
    "Lethal Tempo": "致命节奏",
    "Fleet Footwork": "迅捷步法",
    "Conqueror": "征服者",
    "Triumph": "凯旋",
    "Presence of Mind": "气定神闲",
    "Legend: Alacrity": "传说：欢欣",
    "Legend: Haste": "传说：急速",
    "Legend: Bloodline": "传说：血统",
    "Coup de Grace": "致命一击",
    "Cut Down": "砍倒",
    "Last Stand": "坚毅不倒",
    "Electrocute": "电刑",
    "Dark Harvest": "黑暗收割",
    "Hail of Blades": "丛刃",
    "Cheap Shot": "恶意中伤",
    "Taste of Blood": "血之滋味",
    "Sudden Impact": "猛然冲击",
    "Treasure Hunter": "寻宝猎人",
    "Relentless Hunter": "无情猎手",
    "Ultimate Hunter": "终极猎人",
    "Summon Aery": "召唤：艾黎",
    "Arcane Comet": "奥术彗星",
    "Phase Rush": "相位猛冲",
    "Axiom Arcanist": "公理秘术师",
    "Manaflow Band": "法力流系带",
    "Nimbus Cloak": "灵光披风",
    "Transcendence": "超然",
    "Celerity": "迅捷",
    "Absolute Focus": "绝对专注",
    "Scorch": "焦灼",
    "Waterwalking": "水上行走",
    "Gathering Storm": "风暴聚集",
    "Glacial Augment": "冰川增幅",
    "Unsealed Spellbook": "启封的秘籍",
    "First Strike": "先攻",
    "Cash Back": "返现",
    "Deathfire Touch": "冥火之触",
    "Magical Footwear": "神奇之鞋",
    "Hextech Flashtraption": "海克斯闪现罗网",
    "Biscuit Delivery": "饼干配送",
    "Cosmic Insight": "星界洞悉",
    "Approach Velocity": "行近速率",
    "Time Warp Tonic": "时间扭曲补药",
    "Grisly Mementos": "骇人纪念品",
    "Stormraider's Surge": "风暴骑手的狂涌",
    "Absorb Life": "吸收生命",
    "Deep Ward": "深层守卫",
    "Jack Of All Trades": "多面手",
    "Sixth Sense": "第六感",
    "Triple Tonic": "三重补药",
    "Adaptive Force": "适应之力",
    "Attack Speed": "攻击速度",
    "Ability Haste": "技能急速",
    "Move Speed": "移动速度",
    "Health Scaling": "成长生命值",
    "Flat Health": "生命值",
    "Tenacity and Slow Resist": "韧性和减速抵抗",
}


def item_zh(name: str | None) -> str:
    text = str(name or "")
    return ITEM_ZH.get(text, text)


def rune_zh(name: str | None) -> str:
    text = str(name or "")
    return RUNE_ZH.get(text, text)


def items_zh(items: list[str] | tuple[str, ...] | None) -> list[str]:
    return [item_zh(item) for item in (items or [])]


def runes_zh(runes: list[str] | tuple[str, ...] | None) -> list[str]:
    return [rune_zh(rune) for rune in (runes or [])]
